# Generated by Django 5.2.12 on 2026-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_budget_id_alter_category_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("Income", "Income"), ("Expense", "Expense")],
                default="Expense",
                max_length=7,
            ),
        ),
    ]
