# Generated by Django 5.2.12 on 2026-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="period",
            field=models.CharField(default="Monthly", max_length=10),
        ),
    ]
